# Generated by Django 5.1.4 on 2025-01-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
    ]
